name: nanopore_methylation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - samtools>=1.17
  - minimap2>=2.26
  - bioconda::ont-modkit>=0.3.0
  - qualimap>=2.3
  - pigz
  - parallel
  # R and packages for summary plots
  - r-base>=4.0
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-scales
